on:
  workflow_dispatch:
    inputs:
      git_push_allowed:
        description: "push changes"
        type: boolean
        default: true
      srn_slow:
        description: "Recalculate all srn icons"
        type: boolean
        default: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
          osrs_cache
          runelite
          srn
        key: repos2
    - name: Build with Gradle
      id: build
      run: ./gradlew clean shadowJar
    - name: "Run"
      env:
        KEYS: ${{ secrets.KEYS }}
        GIT_PUSH_ALLOWED: ${{ github.event.inputs.git_push_allowed }}
        SRN_SLOW: ${{ github.event.inputs.srn_slow }}
      run: |
        set -e -x
        echo "$KEYS" | base64 -d | tar -xz -C ~/
        eval $(ssh-agent)
        cat << EOF > ci.properties
        repo.runelite.origin=git@runelite:runelite/runelite-ccau.git
        repo.srn.origin=git@static.runelite.net:runelite/static.runelite.net.git
        git.push.allowed=$GIT_PUSH_ALLOWED
        srn.slow=$SRN_SLOW
        EOF
        cat ci.properties
        export GIT_SSH=ssh
        java -Drlccau.config=ci.properties -cp "build/release/rlccau-$(cat version).jar" net.runelite.cache.codeupdater.Main
    - name: "GC"
      run: |
        git --git-dir runelite/.git repack -ad
        git --git-dir srn/.git repack -ad
